# Site settings
title: miraclew's Blog
email: miraclew@gmail.com
description: "Web development blog!"
baseurl: ""
url: "http://miraclew.github.io/"
twitter_username: miraclewsh
github_username:  miraclew
facebook_username:  miraclew

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
